name: Build

on:
  push:
    branches:
      - main  # Adjust if needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push fitbound image
        working-directory: ./
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/fitbound:${{ vars.BLAH }} .
          docker tag ghcr.io/${{ github.repository_owner }}/fitbound:${{ vars.BLAH }} ghcr.io/${{ github.repository_owner }}/fitbound:${{ github.sha}}
          docker tag ghcr.io/${{ github.repository_owner }}/fitbound:${{ vars.BLAH }} ghcr.io/${{ github.repository_owner }}/fitbound:${{ github.ref_name}}
          docker push ghcr.io/${{ github.repository_owner }}/fitbound:${{ github.ref_name }}
